/*
 * IPGeolocation.io - IP intelligence products
 *
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IPGeolocation.Model;
using IPGeolocation.Client;
using System.Reflection;

namespace IPGeolocation.Test.Model
{
    /// <summary>
    ///  Class for testing Abuse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AbuseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Abuse
        //private Abuse instance;

        public AbuseTests()
        {
            // TODO uncomment below to create an instance of Abuse
            //instance = new Abuse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Abuse
        /// </summary>
        [Fact]
        public void AbuseInstanceTest()
        {
            // TODO uncomment below to test "IsType" Abuse
            //Assert.IsType<Abuse>(instance);
        }

        /// <summary>
        /// Test the property 'Route'
        /// </summary>
        [Fact]
        public void RouteTest()
        {
            // TODO unit test for the property 'Route'
        }

        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

        /// <summary>
        /// Test the property 'Handle'
        /// </summary>
        [Fact]
        public void HandleTest()
        {
            // TODO unit test for the property 'Handle'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Organization'
        /// </summary>
        [Fact]
        public void OrganizationTest()
        {
            // TODO unit test for the property 'Organization'
        }

        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Fact]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }

        /// <summary>
        /// Test the property 'Kind'
        /// </summary>
        [Fact]
        public void KindTest()
        {
            // TODO unit test for the property 'Kind'
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'Emails'
        /// </summary>
        [Fact]
        public void EmailsTest()
        {
            // TODO unit test for the property 'Emails'
        }

        /// <summary>
        /// Test the property 'PhoneNumbers'
        /// </summary>
        [Fact]
        public void PhoneNumbersTest()
        {
            // TODO unit test for the property 'PhoneNumbers'
        }
    }
}
