/*
 * IPGeolocation.io - IP intelligence products
 *
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IPGeolocation.Model;
using IPGeolocation.Client;
using System.Reflection;

namespace IPGeolocation.Test.Model
{
    /// <summary>
    ///  Class for testing AbuseResponseXML
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AbuseResponseXMLTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AbuseResponseXML
        //private AbuseResponseXML instance;

        public AbuseResponseXMLTests()
        {
            // TODO uncomment below to create an instance of AbuseResponseXML
            //instance = new AbuseResponseXML();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AbuseResponseXML
        /// </summary>
        [Fact]
        public void AbuseResponseXMLInstanceTest()
        {
            // TODO uncomment below to test "IsType" AbuseResponseXML
            //Assert.IsType<AbuseResponseXML>(instance);
        }

        /// <summary>
        /// Test the property 'Ip'
        /// </summary>
        [Fact]
        public void IpTest()
        {
            // TODO unit test for the property 'Ip'
        }

        /// <summary>
        /// Test the property 'Abuse'
        /// </summary>
        [Fact]
        public void AbuseTest()
        {
            // TODO unit test for the property 'Abuse'
        }
    }
}
