/*
 * IPGeolocation.io - IP intelligence products
 *
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IPGeolocation.Model;
using IPGeolocation.Client;
using System.Reflection;

namespace IPGeolocation.Test.Model
{
    /// <summary>
    ///  Class for testing AstronomyMorning
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AstronomyMorningTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AstronomyMorning
        //private AstronomyMorning instance;

        public AstronomyMorningTests()
        {
            // TODO uncomment below to create an instance of AstronomyMorning
            //instance = new AstronomyMorning();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AstronomyMorning
        /// </summary>
        [Fact]
        public void AstronomyMorningInstanceTest()
        {
            // TODO uncomment below to test "IsType" AstronomyMorning
            //Assert.IsType<AstronomyMorning>(instance);
        }

        /// <summary>
        /// Test the property 'AstronomicalTwilightBegin'
        /// </summary>
        [Fact]
        public void AstronomicalTwilightBeginTest()
        {
            // TODO unit test for the property 'AstronomicalTwilightBegin'
        }

        /// <summary>
        /// Test the property 'AstronomicalTwilightEnd'
        /// </summary>
        [Fact]
        public void AstronomicalTwilightEndTest()
        {
            // TODO unit test for the property 'AstronomicalTwilightEnd'
        }

        /// <summary>
        /// Test the property 'NauticalTwilightBegin'
        /// </summary>
        [Fact]
        public void NauticalTwilightBeginTest()
        {
            // TODO unit test for the property 'NauticalTwilightBegin'
        }

        /// <summary>
        /// Test the property 'NauticalTwilightEnd'
        /// </summary>
        [Fact]
        public void NauticalTwilightEndTest()
        {
            // TODO unit test for the property 'NauticalTwilightEnd'
        }

        /// <summary>
        /// Test the property 'CivilTwilightBegin'
        /// </summary>
        [Fact]
        public void CivilTwilightBeginTest()
        {
            // TODO unit test for the property 'CivilTwilightBegin'
        }

        /// <summary>
        /// Test the property 'CivilTwilightEnd'
        /// </summary>
        [Fact]
        public void CivilTwilightEndTest()
        {
            // TODO unit test for the property 'CivilTwilightEnd'
        }

        /// <summary>
        /// Test the property 'BlueHourBegin'
        /// </summary>
        [Fact]
        public void BlueHourBeginTest()
        {
            // TODO unit test for the property 'BlueHourBegin'
        }

        /// <summary>
        /// Test the property 'BlueHourEnd'
        /// </summary>
        [Fact]
        public void BlueHourEndTest()
        {
            // TODO unit test for the property 'BlueHourEnd'
        }

        /// <summary>
        /// Test the property 'GoldenHourBegin'
        /// </summary>
        [Fact]
        public void GoldenHourBeginTest()
        {
            // TODO unit test for the property 'GoldenHourBegin'
        }

        /// <summary>
        /// Test the property 'GoldenHourEnd'
        /// </summary>
        [Fact]
        public void GoldenHourEndTest()
        {
            // TODO unit test for the property 'GoldenHourEnd'
        }
    }
}
