/*
 * IPGeolocation.io - IP intelligence products
 *
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IPGeolocation.Model;
using IPGeolocation.Client;
using System.Reflection;

namespace IPGeolocation.Test.Model
{
    /// <summary>
    ///  Class for testing BulkIPSecurityResponse1
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BulkIPSecurityResponse1Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BulkIPSecurityResponse1
        //private BulkIPSecurityResponse1 instance;

        public BulkIPSecurityResponse1Tests()
        {
            // TODO uncomment below to create an instance of BulkIPSecurityResponse1
            //instance = new BulkIPSecurityResponse1();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BulkIPSecurityResponse1
        /// </summary>
        [Fact]
        public void BulkIPSecurityResponse1InstanceTest()
        {
            // TODO uncomment below to test "IsType" BulkIPSecurityResponse1
            //Assert.IsType<BulkIPSecurityResponse1>(instance);
        }
    }
}
