/*
 * IPGeolocation.io - IP intelligence products
 *
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IPGeolocation.Model;
using IPGeolocation.Client;
using System.Reflection;

namespace IPGeolocation.Test.Model
{
    /// <summary>
    ///  Class for testing Location
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LocationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Location
        //private Location instance;

        public LocationTests()
        {
            // TODO uncomment below to create an instance of Location
            //instance = new Location();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Location
        /// </summary>
        [Fact]
        public void LocationInstanceTest()
        {
            // TODO uncomment below to test "IsType" Location
            //Assert.IsType<Location>(instance);
        }

        /// <summary>
        /// Test the property 'ContinentCode'
        /// </summary>
        [Fact]
        public void ContinentCodeTest()
        {
            // TODO unit test for the property 'ContinentCode'
        }

        /// <summary>
        /// Test the property 'ContinentName'
        /// </summary>
        [Fact]
        public void ContinentNameTest()
        {
            // TODO unit test for the property 'ContinentName'
        }

        /// <summary>
        /// Test the property 'CountryCode2'
        /// </summary>
        [Fact]
        public void CountryCode2Test()
        {
            // TODO unit test for the property 'CountryCode2'
        }

        /// <summary>
        /// Test the property 'CountryCode3'
        /// </summary>
        [Fact]
        public void CountryCode3Test()
        {
            // TODO unit test for the property 'CountryCode3'
        }

        /// <summary>
        /// Test the property 'CountryName'
        /// </summary>
        [Fact]
        public void CountryNameTest()
        {
            // TODO unit test for the property 'CountryName'
        }

        /// <summary>
        /// Test the property 'CountryNameOfficial'
        /// </summary>
        [Fact]
        public void CountryNameOfficialTest()
        {
            // TODO unit test for the property 'CountryNameOfficial'
        }

        /// <summary>
        /// Test the property 'CountryCapital'
        /// </summary>
        [Fact]
        public void CountryCapitalTest()
        {
            // TODO unit test for the property 'CountryCapital'
        }

        /// <summary>
        /// Test the property 'StateProv'
        /// </summary>
        [Fact]
        public void StateProvTest()
        {
            // TODO unit test for the property 'StateProv'
        }

        /// <summary>
        /// Test the property 'StateCode'
        /// </summary>
        [Fact]
        public void StateCodeTest()
        {
            // TODO unit test for the property 'StateCode'
        }

        /// <summary>
        /// Test the property 'District'
        /// </summary>
        [Fact]
        public void DistrictTest()
        {
            // TODO unit test for the property 'District'
        }

        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }

        /// <summary>
        /// Test the property 'Zipcode'
        /// </summary>
        [Fact]
        public void ZipcodeTest()
        {
            // TODO unit test for the property 'Zipcode'
        }

        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Fact]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }

        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Fact]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }

        /// <summary>
        /// Test the property 'IsEu'
        /// </summary>
        [Fact]
        public void IsEuTest()
        {
            // TODO unit test for the property 'IsEu'
        }

        /// <summary>
        /// Test the property 'CountryFlag'
        /// </summary>
        [Fact]
        public void CountryFlagTest()
        {
            // TODO unit test for the property 'CountryFlag'
        }

        /// <summary>
        /// Test the property 'GeonameId'
        /// </summary>
        [Fact]
        public void GeonameIdTest()
        {
            // TODO unit test for the property 'GeonameId'
        }

        /// <summary>
        /// Test the property 'CountryEmoji'
        /// </summary>
        [Fact]
        public void CountryEmojiTest()
        {
            // TODO unit test for the property 'CountryEmoji'
        }

        /// <summary>
        /// Test the property 'AccuracyRadius'
        /// </summary>
        [Fact]
        public void AccuracyRadiusTest()
        {
            // TODO unit test for the property 'AccuracyRadius'
        }

        /// <summary>
        /// Test the property 'Locality'
        /// </summary>
        [Fact]
        public void LocalityTest()
        {
            // TODO unit test for the property 'Locality'
        }

        /// <summary>
        /// Test the property 'DmaCode'
        /// </summary>
        [Fact]
        public void DmaCodeTest()
        {
            // TODO unit test for the property 'DmaCode'
        }
    }
}
