/*
 * IPGeolocation.io - IP intelligence products
 *
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IPGeolocation.Model;
using IPGeolocation.Client;
using System.Reflection;

namespace IPGeolocation.Test.Model
{
    /// <summary>
    ///  Class for testing TimezoneDetailDstEnd
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TimezoneDetailDstEndTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TimezoneDetailDstEnd
        //private TimezoneDetailDstEnd instance;

        public TimezoneDetailDstEndTests()
        {
            // TODO uncomment below to create an instance of TimezoneDetailDstEnd
            //instance = new TimezoneDetailDstEnd();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TimezoneDetailDstEnd
        /// </summary>
        [Fact]
        public void TimezoneDetailDstEndInstanceTest()
        {
            // TODO uncomment below to test "IsType" TimezoneDetailDstEnd
            //Assert.IsType<TimezoneDetailDstEnd>(instance);
        }

        /// <summary>
        /// Test the property 'UtcTime'
        /// </summary>
        [Fact]
        public void UtcTimeTest()
        {
            // TODO unit test for the property 'UtcTime'
        }

        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Fact]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }

        /// <summary>
        /// Test the property 'Gap'
        /// </summary>
        [Fact]
        public void GapTest()
        {
            // TODO unit test for the property 'Gap'
        }

        /// <summary>
        /// Test the property 'DateTimeAfter'
        /// </summary>
        [Fact]
        public void DateTimeAfterTest()
        {
            // TODO unit test for the property 'DateTimeAfter'
        }

        /// <summary>
        /// Test the property 'DateTimeBefore'
        /// </summary>
        [Fact]
        public void DateTimeBeforeTest()
        {
            // TODO unit test for the property 'DateTimeBefore'
        }

        /// <summary>
        /// Test the property 'Overlap'
        /// </summary>
        [Fact]
        public void OverlapTest()
        {
            // TODO unit test for the property 'Overlap'
        }
    }
}
