/*
 * IPGeolocation.io - IP intelligence products
 *
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IPGeolocation.Model;
using IPGeolocation.Client;
using System.Reflection;

namespace IPGeolocation.Test.Model
{
    /// <summary>
    ///  Class for testing UserAgentData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserAgentDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserAgentData
        //private UserAgentData instance;

        public UserAgentDataTests()
        {
            // TODO uncomment below to create an instance of UserAgentData
            //instance = new UserAgentData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserAgentData
        /// </summary>
        [Fact]
        public void UserAgentDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserAgentData
            //Assert.IsType<UserAgentData>(instance);
        }

        /// <summary>
        /// Test the property 'UserAgentString'
        /// </summary>
        [Fact]
        public void UserAgentStringTest()
        {
            // TODO unit test for the property 'UserAgentString'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'VersionMajor'
        /// </summary>
        [Fact]
        public void VersionMajorTest()
        {
            // TODO unit test for the property 'VersionMajor'
        }

        /// <summary>
        /// Test the property 'Device'
        /// </summary>
        [Fact]
        public void DeviceTest()
        {
            // TODO unit test for the property 'Device'
        }

        /// <summary>
        /// Test the property 'Engine'
        /// </summary>
        [Fact]
        public void EngineTest()
        {
            // TODO unit test for the property 'Engine'
        }

        /// <summary>
        /// Test the property 'VarOperatingSystem'
        /// </summary>
        [Fact]
        public void VarOperatingSystemTest()
        {
            // TODO unit test for the property 'VarOperatingSystem'
        }
    }
}
