/*
 * IPGeolocation.io - IP intelligence products
 *
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IPGeolocation.Model;
using IPGeolocation.Client;
using System.Reflection;

namespace IPGeolocation.Test.Model
{
    /// <summary>
    ///  Class for testing UserAgentDataOperatingSystem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserAgentDataOperatingSystemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserAgentDataOperatingSystem
        //private UserAgentDataOperatingSystem instance;

        public UserAgentDataOperatingSystemTests()
        {
            // TODO uncomment below to create an instance of UserAgentDataOperatingSystem
            //instance = new UserAgentDataOperatingSystem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserAgentDataOperatingSystem
        /// </summary>
        [Fact]
        public void UserAgentDataOperatingSystemInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserAgentDataOperatingSystem
            //Assert.IsType<UserAgentDataOperatingSystem>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'VersionMajor'
        /// </summary>
        [Fact]
        public void VersionMajorTest()
        {
            // TODO unit test for the property 'VersionMajor'
        }

        /// <summary>
        /// Test the property 'Build'
        /// </summary>
        [Fact]
        public void BuildTest()
        {
            // TODO unit test for the property 'Build'
        }
    }
}
